Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using Delicious_Food_Recipes.Models;
using Delicious_Food_Recipes.Services.Contract.Favorites;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Delicious_Food_Recipes.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly IRecipeService _recipeService;

        public FavoritesController(IRecipeService recipeService)
        {
            _recipeService = recipeService;
        }

        public async Task<IActionResult> AddFavorite(int mealId, string mealImgUrl, string mealName)
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            string userKey = "";

            if (claimUser.Identity.IsAuthenticated)
            {
                userKey = claimUser.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier)
                              .Select(c => c.Value).SingleOrDefault();
            }

            ViewData["userKey"] = userKey;

            if (string.IsNullOrEmpty(userKey))
            {
                return Unauthorized("Kullanıcı kimliği bulunamadı.");
            }

            var existingFavorite = await _recipeService.GetFavoriteAsync(userKey, mealId);

            if (existingFavorite != null)
            {
                return Conflict("Bu tarif zaten favorilerde.");
            }

            var favorite = new Favorite
            {
                UserKey = userKey,
                RecipeId = mealId,
                RecipeImgUrl = mealImgUrl,
                RecipeName = mealName,
                CreatedAt = DateTime.UtcNow
            };

            await _recipeService.AddFavoriteAsync(favorite);

            return RedirectToAction("Details", "Home", new { id = mealId });
        }





        public async Task<IActionResult> RemoveFavorite(int mealId)
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            string userKey = "";

            if (claimUser.Identity.IsAuthenticated)
            {
                userKey = claimUser.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier)
                              .Select(c => c.Value).SingleOrDefault();
            }

            if (string.IsNullOrEmpty(userKey))
            {
                return Unauthorized("Kullanıcı kimliği bulunamadı.");
            }

            var existingFavorite = await _recipeService.GetFavoriteAsync(userKey, mealId);

            if (existingFavorite == null)
            {
                return NotFound("Bu tarif favorilerde bulunmuyor.");
            }

            await _recipeService.RemoveFavoriteAsync(userKey, mealId);

            return RedirectToAction("Details", "Home", new { id = mealId });
        }

        public async Task<IActionResult> MealDetails(int mealId)
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            string userKey = claimUser.Identity.IsAuthenticated ?
                             claimUser.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value : "";

            bool isFavorite = false;

            if (!string.IsNullOrEmpty(userKey))
            {
                var existingFavorite = await _recipeService.GetFavoriteAsync(userKey, mealId);
                isFavorite = existingFavorite != null;
            }

            ViewBag.IsFavorite = isFavorite;

            return View(); // MealDetails.cshtml view'ine yönlendirilir
        }

        public async Task<IActionResult> ListFavorites()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            string userKey = claimUser.Identity.IsAuthenticated ?
                             claimUser.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value : "";

            if (string.IsNullOrEmpty(userKey))
            {
                return Unauthorized("Kullanıcı kimliği bulunamadı.");
            }

            var favorites = await _recipeService.GetAllFavoritesAsync(userKey);
            return View("FavoritesList", favorites);
        }






    }
}

Views/Shared/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApplication</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css?v=@DateTime.Now.Ticks" />
    <style>
        .navbar-brand,
        .nav-link {
            font-size: 1rem; /* Default font size */
        }

        .welcome-username {
            font-size: 1.25rem; /* Larger font size for the username */
            text-align: right; /* Align to the right */
            margin-left: 50px; /* Add some margin to the right */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-custom">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">Delicious Food Recipes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="@Url.Action("Index", "Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Privacy", "Home")">Privacy</a>
                        </li>
                       
                        <a class="nav-link">
                            <span class="welcome-username">Welcome @ViewData["userName"]</span>
                        </a>
                        <li class="nav-item">
                            <a href="@Url.Action("ListFavorites", "Favorites")" class="btn btn-primary">My Favorites</a>

                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <main role="main" class="container my-4">
        @RenderBody()
    </main>
    <footer class="bg-dark text-white py-3 mt-4">
        <div class="container text-center">
            <p>
                &copy; @DateTime.Now.Year - Delicious Food Recipes
            </p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>